spring:
  application:
    name: api-tm
  liquibase:
    changelog: "classpath:db/changelog/changelog.xml"
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/tm
