server:
  port: 8080
jwt:
  secret: 383jf23zae2j9322fj39f39ffuckkk9r5632fjwt
  lifetime: 50m
spring:
  application:
    name: api-tm
  liquibase:
    changelog: "classpath:db/changelog/changelog.xml"
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/tm
  security:
    user:
      name: user
      password: user
